# Generated by Django 4.2.11 on 2026-05-28 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedEmissionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP ERP Export'), ('UTILITY', 'Utility Portal CSV'), ('CONCUR', 'Corporate Travel API')], max_length=20)),
                ('scope_category', models.CharField(choices=[('Scope 1', 'Scope 1: Direct Emissions'), ('Scope 2', 'Scope 2: Indirect Emissions'), ('Scope 3', 'Scope 3: Other Indirect Emissions')], max_length=10)),
                ('activity_type', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('raw_quantity', models.FloatField()),
                ('raw_unit', models.CharField(max_length=50)),
                ('normalized_quantity', models.FloatField()),
                ('normalized_unit', models.CharField(max_length=50)),
                ('calculated_co2e_kg', models.FloatField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved for Audit'), ('REJECTED', 'Rejected / Flagged')], default='PENDING', max_length=10)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('anomaly_reason', models.TextField(blank=True, null=True)),
                ('raw_payload_snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('previous_state', models.JSONField(blank=True, null=True)),
                ('new_state', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ingestion.normalizedemissiondata')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
